import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers/providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["700", "600", "400"],
});
export const metadata: Metadata = {
  title: "Online Exam Elevate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
